steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
    # TODO: "--global" is unsafe for multi-agent CI machines.  We're using it here as a temporary workaround
    # for a limitation of "docusaurus deploy".  Revert this to "--local" as soon as Docusaurus is fixed.
  - script: 'git config --global user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'
  - script: 'git config --global user.name Rushbot'
    displayName: 'git config name'
  - script: 'node common/scripts/install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'
  - script: 'node common/scripts/install-run-rush.js build --verbose --to api-extractor.com --to tsdoc.org'
    displayName: 'Rush Build'
    env:
      # Prevent time-based browserslist update warning
      # See https://github.com/microsoft/rushstack/issues/2981
      BROWSERSLIST_IGNORE_OLD_DATA: 1
